-- skyh00k Line Book table — run once in Supabase SQL Editor
create table if not exists lines (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  slate_date date not null,
  league text not null,
  game_id text not null,
  player_id bigint not null,
  player_name text,
  book text not null default 'dk',
  odds text not null
);

alter table lines enable row level security;

-- personal app: anon key may read and insert (no update/delete from client)
create policy "lines readable" on lines for select using (true);
create policy "lines insertable" on lines for insert with check (true);
